### ISSUE TITLE
Hello lol

### ISSUE THREAD

**Issue by Zazanels** [Coyote21/Food-Remover-Plus#2]
It's me again 😁 today I have that error : 

RecordException mihailsewerrat.esp => DFC714:Skyrim.esm<WorldspaceSubBlock>: Stream asked to to move to a position that was too large: 2515393456.  Major Meta reported a TotalLength of 2515393168 System.OverflowException: Stream asked to to move to a position that was too large: 2515393456.  Major Meta reported a TotalLength of 2515393168
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillMajorRecords(OverlayStream stream, Int32 finalPos, Int32 offset, TypedParseParams translationParams, RecordTypeFillWrapper fill)   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.<>c__DisplayClass35_0`2.<EnumerateMajorRecordContexts>b__1(Exception e)
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 287
   at Mutagen.Bethesda.OverrideMixIns.WinningOverrideContexts[TMod,TModGetter,TSetter,TGetter](IEnumerable`1 mods, ILinkCache linkCache, Boolean includeDeletedRecords)+MoveNext()
   at FoodRemoverPlus.Program.RunPatch(IPatcherState`2 state) in C:\Users\Greg\AppData\Local\Temp\Synthesis\yxxakz3d.eoa\Git\apwubdq1.leu\Runner\FoodRemoverPlus\Program.cs:line 125
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass16_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 106
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 631
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass45_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 496
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 881
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 484
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass44_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 456

😢

**Comment by Noggog** [comment]
`mihailsewerrat.esp` seems like it might be a corrupted file.  Can you provide a link to where it's from?

**Comment by Zazanels** [comment]
Of course, it's from https://www.nexusmods.com/skyrimspecialedition/mods/99292

**Comment by Zazanels** [comment]
Also same plugin giving an error with https://github.com/Deigue/CellEncounterLevelsInName

**Comment by Coyote21** [comment]
So I just downloaded that mod. I put it into a vanilla build (Skyrim AE but with only 4 free CC mods). Tested mihailsewerrat.esp in xEdit looks fine.

Used my patcher on the LO (Skyrim AE + CCs + milhailsewerrat.esp), No errors, no problems. Opened resulting FoodRemover.esp in xEdit and everything looks as it should.

I can only assume it's either an issue when used with one of the other patchers, some other mod in your LO or perhaps even a combination of both?

Can only suggest re-testing adding only one patcher at a time to try to narrow down the cause, and/or use a similar process on your LO.

**Comment by Noggog** [comment]
I also ran the mod through my passthrough tests in mutagen, and it turned up okay so far.   Are you sure you haven't modified the file?   Maybe redownload it fresh and confirm

**Comment by Zazanels** [comment]
When patching with these no issues : https://imgur.com/SMkB1XC

But with one of the two next patchers, the same plugin is blocking : https://imgur.com/pWzjXag

So I really think that plugin cause an issue but you're right I have a pretty big load order with 900 plugins so it can be something else. Will try to rebuilt without that plugin ( need to rebuild smashed patch as well) and will tell you.

**Comment by Noggog** [comment]
Patchers only parse what they interact with, so it might be that the ones that are working just interacting with the offending record (not interested in that GRUP, perhaps)

Have you confirmed your `mihailsewerrat.esp` hasn't been modified?  If so, can you upload here just to confirm?

**Comment by Zazanels** [comment]
Sorry no I haven't modified mihailsewerrat.esp in any way !

**Comment by Coyote21** [comment]
Not saying the modification is deliberate... It could just be ordinary file corruption from download, OS, AV etc. If you can upload a copy we 'know' we are seeing the same file you are, instead of a copy from the same source.

**Comment by Zazanels** [comment]
Ok will do it later. I'm in Europe so it's late (more early), see you tomorrow guys and thanks.

**Comment by hoskonen** [comment]
Is there some recommended settings for this new one, since it takes so much time compared to the old one. I waited for 10 minutes and then canceled.

**Comment by Noggog** [comment]
> Is there some recommended settings for this new one, since it takes so much time compared to the old one. I waited for 10 minutes and then canceled.

@hoskonen Hey, i think you should create a new issue in github with your problem.  I'm going to close this current issue out, as I think it's stale and has dead-ended

Open up that new issue, and I can take a look and chat there!
